### ISSUE TITLE
Iteration card displays latest update or warning 

### ISSUE THREAD

**Issue by suninthesky** [TechforgoodCAST/fusebox-insights#117]
Requires accompanying tests.

![Screenshot 2019-08-29 at 17 03 20](https://user-images.githubusercontent.com/7393302/63956750-f4026b00-ca7e-11e9-8e63-c9e812b26511.png)

**Comment by suninthesky** [comment]
@jdudley1123 just noticed we've not accounted for the completed debrief state, are you okay to implement something similar to how we show the latest check-in?

**Comment by jdudley1123** [comment]
Isn't that covered by this? https://github.com/TechforgoodCAST/fusebox-insights/pull/149/commits/637c9fd3ea62f3b179b2c0e3e50fe1f664401e7b#diff-2476f44a5f0802d146b181eeb56e8a12R130

**Comment by suninthesky** [comment]
It does but I think the status of iterations isn't being updated when debriefs are created, running `#update!` raises this validation error...

<img width="738" alt="Screenshot 2019-09-17 at 13 52 26" src="https://user-images.githubusercontent.com/7393302/65043223-68c81700-d952-11e9-812e-8e3427fb6b15.png">

Something like `validate :start_date_cannot_be_in_the_past, if: :status_committed?` on `Iteration` might resolve this.

**Comment by jdudley1123** [comment]
This led me down a bit of a rabbit hole because there was a bug with the milestones being linked to debriefs, but I think it's all sorted now.

**Comment by jdudley1123** [comment]
I was wrong, it wasn't all sorted, but it is now. I hope...
