### ISSUE TITLE
Contributors and mentors are notified when a check-in is completed

### ISSUE THREAD

**Issue by suninthesky** [TechforgoodCAST/fusebox-insights#119]
Requires accompanying system tests.

**Comment by suninthesky** [comment]
Could use this [method](https://github.com/TechforgoodCAST/fusebox-insights/blob/issue-121/app/mailers/notifications_mailer.rb#L31-L33) to send this message to all contributors and mentors. Also suggest that the email template should link to the iteration rather than project.

**Comment by jdudley1123** [comment]
I think that method's only in your branch rather than in dev at the moment.

**Comment by suninthesky** [comment]
That's right - we could use it to simplify the logic in `check_ins_controller.rb` once merged.

**Comment by jdudley1123** [comment]
If we do `mail to: emails`, does that send one email to multiple recipients (ie. they can all see each other) or several individual emails? Which behaviour do we want for notifications?

I'm leaning towards the former as it'll make it clear who else in your team received it.

**Comment by suninthesky** [comment]
It sends one email with multiple recipients.

Agree - I designed it with the idea of making it clear who else in the team received the email (at least for this version).
