### ISSUE TITLE
Authorise access to check ins

### ISSUE THREAD

**Issue by suninthesky** [TechforgoodCAST/fusebox-insights#122]
- Prevent access to stakeholders
- Hide when viewing iteration as stakeholder
- ~(TBC) Prevent check-ins within two weeks of the last~

Requires accompanying tests.

**Comment by jdudley1123** [comment]
- ~Prevent access to stakeholders~
- ~Hide when viewing iteration as stakeholder~

Have added unit and systems tests.

**Comment by suninthesky** [comment]
I can't see the commits, could you push and make a pull request into `dev` branch.

**Comment by suninthesky** [comment]
Resolved with #147
